apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-ml-console-httpproxy
  namespace: ${MINIO_BUCKET_NAMESPACE}
spec:
  virtualhost:
    fqdn: minio-ml-console.${MLFLOW_INGRESS_DOMAIN}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: minio
          port: 9001
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-ml-httpproxy
  namespace: ${MINIO_BUCKET_NAMESPACE}
spec:
  virtualhost:
    fqdn: ${MLFLOW_S3_ENDPOINT_FQDN}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: minio
          port: 9000
    
