---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  chart:
    spec:
      chart: mlflow
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mlflow
        namespace: mlflow
      version: '1.0.4'
  install:
    createNamespace: true
  interval: 5m0s
  targetNamespace: mlflow
  valuesFrom:
    - kind: ConfigMap
      name: mlflowvalues
