---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mlflow-server-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: mlflow-server-tap
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  env:
    - name: BP_WEB_SERVER
      value: nginx
  source:
    git:
      url: https://github.com/agapebondservant/mlflow-accelerator.git
      ref:
        branch: tap